export const LineColorMap: { [lineId: string]: string } = {
  '1': '--color-line-red',
  '2': '--color-line-red',
  '3': '--color-line-red',
  '4': '--color-line-green',
  '5': '--color-line-green',
  '6': '--color-line-green',
  '7': '--color-line-purple',
  A: '--color-line-blue',
  C: '--color-line-blue',
  E: '--color-line-blue',
  B: '--color-line-orange',
  D: '--color-line-orange',
  F: '--color-line-orange',
  M: '--color-line-orange',
  G: '--color-line-lightGreen',
  J: '--color-line-brown',
  Z: '--color-line-brown',
  L: '--color-line-gray',
  S: '--color-line-gray',
  N: '--color-line-yellow',
  Q: '--color-line-yellow',
  R: '--color-line-yellow',
  W: '--color-line-yellow',
};
