schema {
  query: Query
}

type Query {
  getNearbyStations(lat: String!, lon: String!): [Station!]
  getStation(id: ID!): Station
  getStations(search: String): [Station!]!
}

type Line {
  id: ID!
  color: String!
  stations: [Station!]!
}

type Station {
  id: ID!
  name: String!
  line: Line!
  coordinates: {
    lat: String!
    lon: String!
  }
  platforms: [StationLine!]!
}

type StationLine {
  line: Line!
  status: StationPlatformStatus!
  type: StationPlatformType!
  directions: [StationLineDirection!]!
}

type StationLineDirection {
  name: String!
  times: [StationLineDirectionTime!]!
}

type StationLineDirectionTime {
  minutes: Number!
  lastStation: Station!
}

enum StationPlatformType {
  ALWAYS_STOP
  MIGHT_SKIP
  NIGHTS_ONLY
  RUSH_ONLY
};

enum StationPlatformStatus {
  NORMAL
  CLOSED
  SOUTHBOUND_CLOSED
  NORTHBOUND_CLOSED
};